# Generated by Django 6.0.2 on 2026-02-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('accelerometer', 'Accelerometer'), ('gyroscope', 'Gyroscope'), ('gps', 'GPS'), ('audio', 'Audio')], max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('data_json', models.JSONField(help_text='Raw sensor data in JSON format')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_timestamp', models.DateTimeField(auto_now_add=True)),
                ('accelerometer_risk_score', models.FloatField(default=0.0)),
                ('audio_risk_score', models.FloatField(default=0.0)),
                ('location_risk_score', models.FloatField(default=0.0)),
                ('fused_risk_score', models.FloatField(help_text='Combined risk score from all modalities')),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('confidence_level', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_detections', to=settings.AUTH_USER_MODEL)),
                ('accelerometer_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accelerometer_detections', to='safety.sensordata')),
                ('audio_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_detections', to='safety.sensordata')),
            ],
            options={
                'ordering': ['-detection_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(help_text='Audio duration in seconds')),
                ('sample_rate', models.IntegerField()),
                ('mfcc_features', models.JSONField(help_text='MFCC features array')),
                ('spectral_centroid', models.FloatField(blank=True, null=True)),
                ('zero_crossing_rate', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('scream_probability', models.FloatField(default=0.0)),
                ('distress_probability', models.FloatField(default=0.0)),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_features', to='safety.sensordata')),
            ],
        ),
        migrations.CreateModel(
            name='AccelerometerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.FloatField()),
                ('y_axis', models.FloatField()),
                ('z_axis', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('sudden_change_detected', models.BooleanField(default=False)),
                ('fall_detected', models.BooleanField(default=False)),
                ('shake_detected', models.BooleanField(default=False)),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accelerometer_readings', to='safety.sensordata')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('priority', models.IntegerField(default=1, help_text='Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'name'],
                'unique_together': {('user', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('email', 'Email'), ('call', 'Emergency Call')], max_length=50)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('emergency_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='safety.emergencydetection')),
            ],
            options={
                'indexes': [models.Index(fields=['emergency_detection', 'sent_at'], name='safety_aler_emergen_5f21c2_idx'), models.Index(fields=['delivery_status'], name='safety_aler_deliver_e129ef_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['user', 'sensor_type', 'timestamp'], name='safety_sens_user_id_466896_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['timestamp'], name='safety_sens_timesta_abadfe_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['latitude', 'longitude'], name='safety_sens_latitud_41159d_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencydetection',
            index=models.Index(fields=['user', 'detection_timestamp'], name='safety_emer_user_id_930500_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencydetection',
            index=models.Index(fields=['is_emergency'], name='safety_emer_is_emer_afd764_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencydetection',
            index=models.Index(fields=['fused_risk_score'], name='safety_emer_fused_r_48b45f_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencydetection',
            index=models.Index(fields=['latitude', 'longitude'], name='safety_emer_latitud_a8c357_idx'),
        ),
    ]
