# Generated by Django 6.0.2 on 2026-02-10 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio_mfcc', models.JSONField(help_text='MFCC features')),
                ('location', models.JSONField(blank=True, help_text='Lat, Lon', null=True)),
                ('distress_probability', models.FloatField()),
                ('emergency_triggered', models.BooleanField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accelerometer_data', models.JSONField(help_text='Accelerometer x, y, z')),
                ('gyroscope_data', models.JSONField(help_text='Gyroscope x, y, z')),
                ('anomaly_score', models.FloatField()),
                ('anomaly_detected', models.BooleanField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='emergencydetection',
            name='safety_emer_latitud_a8c357_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensordata',
            name='safety_sens_latitud_41159d_idx',
        ),
        migrations.AddField(
            model_name='audioevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='audio_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='safety.audioevent'),
        ),
        migrations.AddField(
            model_name='sensorevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
