# Generated by Django 6.0.2 on 2026-02-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dataset_type', models.CharField(choices=[('risk_scoring', 'Risk Scoring Data'), ('audio_samples', 'Audio Samples'), ('sensor_data', 'Sensor Data'), ('route_data', 'Route Data')], max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('num_samples', models.IntegerField()),
                ('num_features', models.IntegerField()),
                ('feature_names', models.JSONField()),
                ('completeness_score', models.FloatField(blank=True, help_text='Percentage of complete records', null=True)),
                ('balance_score', models.FloatField(blank=True, help_text='Class balance score', null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_type', models.CharField(choices=[('risk_scoring', 'Risk Scoring Model'), ('audio_classification', 'Audio Classification Model'), ('anomaly_detection', 'Anomaly Detection Model'), ('route_optimization', 'Route Optimization Model')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('model_file_path', models.CharField(help_text='Path to model file', max_length=500)),
                ('input_features', models.JSONField(help_text='List of input feature names')),
                ('output_classes', models.JSONField(blank=True, help_text='Output classes for classification models', null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_production', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='ml_engine_m_model_t_4e1c84_idx'), models.Index(fields=['is_production'], name='ml_engine_m_is_prod_abef5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('importance_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_importances', to='ml_engine.mlmodel')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('model', 'feature_name')},
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('num_predictions', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('avg_confidence', models.FloatField(blank=True, null=True)),
                ('false_positive_rate', models.FloatField(blank=True, null=True)),
                ('false_negative_rate', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='ml_engine.mlmodel')),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'indexes': [models.Index(fields=['model', 'evaluation_date'], name='ml_engine_m_model_i_eb74a2_idx')],
                'unique_together': {('model', 'evaluation_date')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Input features used for prediction')),
                ('prediction_result', models.JSONField(help_text='Model output/prediction')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence level of prediction', null=True)),
                ('prediction_type', models.CharField(max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('actual_outcome', models.JSONField(blank=True, help_text='Actual outcome for model evaluation', null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_engine.mlmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['model', 'predicted_at'], name='ml_engine_p_model_i_c20c73_idx'), models.Index(fields=['user', 'prediction_type'], name='ml_engine_p_user_id_fc68cb_idx')],
            },
        ),
    ]
