# Generated by Django 6.0.2 on 2026-02-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('location_type', models.CharField(choices=[('waypoint', 'Waypoint'), ('landmark', 'Landmark'), ('intersection', 'Intersection')], default='waypoint', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_loc_latitud_015195_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(help_text='Distance in kilometers')),
                ('estimated_duration', models.FloatField(help_text='Duration in minutes')),
                ('overall_risk_score', models.FloatField()),
                ('route_type', models.CharField(choices=[('safest', 'Safest Route'), ('fastest', 'Fastest Route'), ('balanced', 'Balanced Route')], default='safest', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='routing.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='routing.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('waypoints', models.ManyToManyField(blank=True, related_name='route_waypoints', to='routing.location')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField()),
                ('segment_distance', models.FloatField()),
                ('segment_duration', models.FloatField()),
                ('segment_risk_score', models.FloatField()),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_ends', to='routing.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='routing.route')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_starts', to='routing.location')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.FloatField(help_text='Risk score between 0.0 and 1.0')),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('crime_rate', models.FloatField(blank=True, null=True)),
                ('lighting_score', models.FloatField(blank=True, null=True)),
                ('crowd_density', models.FloatField(blank=True, null=True)),
                ('incident_history', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='routing.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'time_of_day'], name='routing_ris_locatio_e5da6e_idx'), models.Index(fields=['risk_level'], name='routing_ris_risk_le_b2f636_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['user', 'is_active'], name='routing_rou_user_id_1a79ed_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['created_at'], name='routing_rou_created_fbd106_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routesegment',
            unique_together={('route', 'sequence_order')},
        ),
    ]
