# Generated by Django 4.2.28 on 2026-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='path_data',
            field=models.JSONField(blank=True, default=list, help_text='List of {lat, lng, risk} points'),
        ),
    ]
